export type DashboardViewType =
  | 'USER_DASHBOARD' | 'USERS_CRUD'
  | 'EMPLOYEES_CRUD' | 'EMPLOYEE_DASHBOARD' | 'EMPLOYEE_DETAIL'
  | 'VEHICLES_CRUD' | 'VEHICLE_DASHBOARD' | 'VEHICLE_DETAIL'
  | 'WORK_CENTERS_CRUD' | 'WORK_CENTERS_DASHBOARD'
  | 'SERVICES_CRUD' | 'SERVICES_DASHBOARD' | 'SERVICE_DETAIL'
  | 'INVENTORY_CRUD' | 'INVENTORY_DASHBOARD'
  | 'SERVICE_REPORT'
  | 'WORK_REPORT'
  | 'PROFILE' | 'PROFILE_CONFIG'
  | 'TESTS_AUTH' | 'TESTS_JWT' | 'TESTS_CRUD' | 'TESTS_RBAC' | 'TESTS_ROLES'
  | 'LOGS_AUTH' | 'LOGS_LOGOUT' | 'LOGS_USERS' | 'LOGS_EMPLOYEES'
  | 'UTILS'
  | 'UTILS_LOGS'
  | 'UTILS_TESTS';

export const VIEW_ROLES: Record<DashboardViewType, string[]> = {
  USER_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  USERS_CRUD: ['ROOT', 'ADMIN'],
  EMPLOYEES_CRUD: ['ROOT', 'ADMIN'],
  EMPLOYEE_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  EMPLOYEE_DETAIL: ['ROOT', 'ADMIN'],
  VEHICLES_CRUD: ['ROOT', 'ADMIN'],
  VEHICLE_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  VEHICLE_DETAIL: ['ROOT', 'ADMIN'],
  WORK_CENTERS_CRUD: ['ROOT', 'ADMIN'],
  WORK_CENTERS_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  SERVICES_CRUD: ['ROOT', 'ADMIN'],
  SERVICES_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  SERVICE_DETAIL: ['ROOT', 'ADMIN'],
  INVENTORY_CRUD: ['ROOT', 'ADMIN'],
  INVENTORY_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  SERVICE_REPORT: ['ROOT', 'MANAGER'],
  WORK_REPORT: ['ROOT', 'ADMIN', 'MANAGER', 'USER'],
  PROFILE: ['ROOT', 'ADMIN', 'MANAGER', 'USER'],
  PROFILE_CONFIG: ['ROOT', 'ADMIN', 'MANAGER', 'USER'],
  TESTS_AUTH: ['ROOT', 'ADMIN', 'MANAGER'],
  TESTS_JWT: ['ROOT', 'ADMIN', 'MANAGER'],
  TESTS_CRUD: ['ROOT', 'ADMIN', 'MANAGER'],
  TESTS_RBAC: ['ROOT', 'ADMIN', 'MANAGER'],
  TESTS_ROLES: ['ROOT', 'ADMIN', 'MANAGER'],
  LOGS_AUTH: ['ROOT', 'ADMIN'],
  LOGS_LOGOUT: ['ROOT', 'ADMIN'],
  LOGS_USERS: ['ROOT', 'ADMIN'],
  LOGS_EMPLOYEES: ['ROOT', 'ADMIN'],
  UTILS: ['ROOT', 'ADMIN', 'MANAGER'],
  UTILS_LOGS: ['ROOT', 'ADMIN'],
  UTILS_TESTS: ['ROOT', 'ADMIN'],
};
