export type DashboardViewType =
  | 'USER_DASHBOARD' | 'USERS_CRUD'
  | 'EMPLOYEES_CRUD' | 'EMPLOYEE_DASHBOARD' | 'EMPLOYEE_DETAIL'
  | 'VEHICLES_CRUD' | 'VEHICLE_DASHBOARD' | 'VEHICLE_DETAIL'
  | 'WORK_CENTERS_CRUD' | 'WORK_CENTERS_DASHBOARD'
  | 'SERVICES_CRUD' | 'SERVICES_DASHBOARD' | 'SERVICE_DETAIL'
  | 'INVENTORY_CRUD' | 'INVENTORY_DASHBOARD'
  | 'MACHINERY_CRUD' | 'MACHINERY_DASHBOARD'
  | 'SERVICE_REPORT'
  | 'WORK_REPORT'
  | 'PROFILE' | 'PROFILE_CONFIG';

export const VIEW_ROLES: Record<DashboardViewType, string[]> = {
  USER_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  USERS_CRUD: ['ROOT', 'ADMIN'],
  EMPLOYEES_CRUD: ['ROOT', 'ADMIN'],
  EMPLOYEE_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  EMPLOYEE_DETAIL: ['ROOT', 'ADMIN'],
  VEHICLES_CRUD: ['ROOT', 'ADMIN'],
  VEHICLE_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  VEHICLE_DETAIL: ['ROOT', 'ADMIN'],
  WORK_CENTERS_CRUD: ['ROOT', 'ADMIN'],
  WORK_CENTERS_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  SERVICES_CRUD: ['ROOT', 'ADMIN'],
  SERVICES_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  SERVICE_DETAIL: ['ROOT', 'ADMIN'],
  INVENTORY_CRUD: ['ROOT', 'ADMIN'],
  INVENTORY_DASHBOARD: ['ROOT', 'ADMIN', 'MANAGER'],
  MACHINERY_CRUD: ['ROOT', 'ADMIN'],
  MACHINERY_DASHBOARD: ['ROOT', 'ADMIN'],
  SERVICE_REPORT: ['ROOT', 'MANAGER'],
  WORK_REPORT: ['ROOT', 'ADMIN', 'MANAGER', 'USER'],
  PROFILE: ['ROOT', 'ADMIN', 'MANAGER', 'USER'],
  PROFILE_CONFIG: ['ROOT', 'ADMIN', 'MANAGER', 'USER'],

};
