export type DashboardViewType =
  | 'USER_DASHBOARD' | 'USERS_CRUD'
  | 'EMPLOYEES_CRUD' | 'EMPLOYEE_DASHBOARD' | 'EMPLOYEE_DETAIL'
  | 'VEHICLES_CRUD' | 'VEHICLE_DASHBOARD' | 'VEHICLE_DETAIL'
  | 'WORK_CENTERS_CRUD' | 'WORK_CENTERS_DASHBOARD'
  | 'SERVICES_CRUD' | 'SERVICES_DASHBOARD' | 'SERVICE_DETAIL'
  | 'INVENTORY_CRUD' | 'INVENTORY_DASHBOARD'
  | 'PROFILE'
  | 'TESTS_AUTH' | 'TESTS_JWT' | 'TESTS_CRUD' | 'TESTS_RBAC' | 'TESTS_ROLES'
  | 'LOGS_AUTH' | 'LOGS_LOGOUT' | 'LOGS_USERS' | 'LOGS_EMPLOYEES'
  | 'UTILS';
